const TOOLS=[
{name:"link_dashboard",description:"Estado ejecutivo del Sales OS.",inputSchema:{type:"object",properties:{}}},
{name:"link_search_prospects",description:"Busca prospectos por texto, etapa, industria o ciudad.",inputSchema:{type:"object",properties:{query:{type:"string"},status:{type:"string"},industry:{type:"string"},city:{type:"string"},limit:{type:"number"}}}},
{name:"link_hunt_prospects",description:"Busca comercios con Google Places y prioriza negocios sin website.",inputSchema:{type:"object",properties:{city:{type:"string"},industry:{type:"string"},limit:{type:"number"},persist:{type:"boolean"}}}},
{name:"link_get_client",description:"Obtiene ficha 360 del cliente.",inputSchema:{type:"object",properties:{client_id:{type:"string"}},required:["client_id"]}},
{name:"link_update_pipeline",description:"Mueve un prospecto de etapa y define próxima acción.",inputSchema:{type:"object",properties:{prospect_id:{type:"string"},stage:{type:"string"},next_action:{type:"string"},next_action_at:{type:"string"}},required:["prospect_id","stage"]}},
{name:"link_create_task",description:"Crea una acción comercial.",inputSchema:{type:"object",properties:{title:{type:"string"},client_id:{type:"string"},prospect_id:{type:"string"},due_at:{type:"string"},priority:{type:"string"},notes:{type:"string"}},required:["title"]}},
{name:"link_add_memory",description:"Agrega memoria a la inteligencia del cliente.",inputSchema:{type:"object",properties:{client_id:{type:"string"},title:{type:"string"},content:{type:"string"},kind:{type:"string"}},required:["client_id","content"]}},
{name:"link_add_source",description:"Agrega una fuente documental al cliente.",inputSchema:{type:"object",properties:{client_id:{type:"string"},title:{type:"string"},source_url:{type:"string"},content:{type:"string"},kind:{type:"string"}},required:["client_id","content"]}},
{name:"link_create_preview",description:"Genera una Preview Factory específica para un prospecto.",inputSchema:{type:"object",properties:{prospect_id:{type:"string"},name:{type:"string"},industry:{type:"string"},city:{type:"string"},website:{type:"string"},sales_channel:{type:"string"},friction:{type:"string"},objective:{type:"string"}},required:["name","industry"]}},
{name:"link_ingest_document",description:"Convierte un documento de cliente en chunks y embeddings pgvector.",inputSchema:{type:"object",properties:{client_id:{type:"string"},title:{type:"string"},source_url:{type:"string"},content:{type:"string"},kind:{type:"string"}},required:["client_id","content"]}},
{name:"link_notebook_query",description:"Consulta la inteligencia semántica del cliente y responde con fuentes recuperadas.",inputSchema:{type:"object",properties:{client_id:{type:"string"},question:{type:"string"},limit:{type:"number"}},required:["client_id","question"]}},
{name:"link_build_sales_batch",description:"Ejecuta la maquinaria: busca prospectos, selecciona los mejores, genera previews, registra oportunidades y crea seguimientos.",inputSchema:{type:"object",properties:{city:{type:"string"},industry:{type:"string"},limit:{type:"number"},top:{type:"number"},followup_days:{type:"number"}}}},
{name:"link_ask_client_ai",description:"Consulta la IA contextual del cliente.",inputSchema:{type:"object",properties:{client_id:{type:"string"},question:{type:"string"}},required:["client_id","question"]}}
];
function auth(req){const expected=process.env.MCP_ACCESS_TOKEN;if(!expected)return true;return String(req.headers.authorization||"")===`Bearer ${expected}`}
async function supa(path,opts={}){const base=(process.env.SUPABASE_URL||"").replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!base||!key)throw new Error("Supabase server configuration missing");const r=await fetch(`${base}/rest/v1/${path}`,{...opts,headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",Prefer:"return=representation",...(opts.headers||{})}});const text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch{}if(!r.ok)throw new Error(d.message||d.hint||`Supabase HTTP ${r.status}`);return d}
function result(data){return {content:[{type:"text",text:JSON.stringify(data,null,2)}]}}
async function internal(path,body){const base=(process.env.APP_URL||`https://${process.env.VERCEL_URL||"localhost"}`).replace(/\/$/,"");const h={"Content-Type":"application/json"};if(process.env.MCP_ACCESS_TOKEN)h.Authorization=`Bearer ${process.env.MCP_ACCESS_TOKEN}`;const r=await fetch(`${base}${path}`,{method:"POST",headers:h,body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||`Internal API ${r.status}`);return d}
async function clientContext(id){const [c,m,s,o,t]=await Promise.all([supa(`clients?id=eq.${encodeURIComponent(id)}&select=*`),supa(`client_memories?client_id=eq.${encodeURIComponent(id)}&select=*&order=created_at.desc&limit=50`),supa(`client_sources?client_id=eq.${encodeURIComponent(id)}&select=*&order=created_at.desc&limit=50`),supa(`opportunities?client_id=eq.${encodeURIComponent(id)}&select=*&order=updated_at.desc&limit=50`),supa(`tasks?client_id=eq.${encodeURIComponent(id)}&select=*&order=due_at.asc&limit=50`)]);return {client:c?.[0]||null,memories:m,sources:s,opportunities:o,tasks:t}}
async function callTool(name,a){switch(name){
case"link_dashboard":{const[p,c,t,e]=await Promise.all([supa("prospects?select=id,name,stage,score,next_action,next_action_at&order=score.desc&limit=100"),supa("clients?select=id,name,status,next_action,next_action_at&order=updated_at.desc&limit=100"),supa("tasks?select=id,title,status,priority,due_at&order=due_at.asc&limit=50"),supa("calendar_events?select=id,title,start_at,end_at,status&order=start_at.asc&limit=50")]);return result({prospects:p,clients:c,tasks:t,calendar:e})}
case"link_search_prospects":{const parts=["select=*","order=score.desc,updated_at.desc",`limit=${Math.min(Number(a.limit)||20,100)}`];if(a.status)parts.push(`stage=eq.${encodeURIComponent(a.status)}`);if(a.industry)parts.push(`industry=ilike.*${encodeURIComponent(a.industry)}*`);if(a.city)parts.push(`city=ilike.*${encodeURIComponent(a.city)}*`);if(a.query){const q=encodeURIComponent(a.query);parts.push(`or=(name.ilike.*${q}*,website.ilike.*${q}*,instagram.ilike.*${q}*)`)}return result(await supa(`prospects?${parts.join("&")}`))}
case"link_hunt_prospects":return result(await internal("/api/prospect-hunter",{city:a.city||"Copiapó",industry:a.industry||"comercio local",limit:a.limit||20,persist:a.persist!==false}));
case"link_get_client":return result(await clientContext(a.client_id));
case"link_update_pipeline":{const patch={stage:a.stage,updated_at:new Date().toISOString()};if(a.next_action!==undefined)patch.next_action=a.next_action;if(a.next_action_at!==undefined)patch.next_action_at=a.next_action_at;return result(await supa(`prospects?id=eq.${encodeURIComponent(a.prospect_id)}`,{method:"PATCH",body:JSON.stringify(patch)}))}
case"link_create_task":return result(await supa("tasks",{method:"POST",body:JSON.stringify({title:a.title,client_id:a.client_id||null,prospect_id:a.prospect_id||null,due_at:a.due_at||null,priority:a.priority||"media",notes:a.notes||"",status:"pendiente",owner_id:process.env.LINK_OWNER_ID||null})}));
case"link_add_memory":return result(await supa("client_memories",{method:"POST",body:JSON.stringify({client_id:a.client_id,title:a.title||"Memoria LINK",content:a.content,kind:a.kind||"insight",owner_id:process.env.LINK_OWNER_ID||null})}));
case"link_add_source":return result(await supa("client_sources",{method:"POST",body:JSON.stringify({client_id:a.client_id,title:a.title||"Fuente",source_url:a.source_url||null,content:a.content,kind:a.kind||"note",owner_id:process.env.LINK_OWNER_ID||null})}));
case"link_create_preview":{let p={...a};if(a.prospect_id){const rows=await supa(`prospects?id=eq.${encodeURIComponent(a.prospect_id)}&select=*`);p={...(rows?.[0]||{}),...a}}return result(await internal("/api/preview-factory",{prospect:p}))}
case"link_ingest_document":return result(await internal("/api/intelligence-ingest",a));
case"link_notebook_query":return result(await internal("/api/intelligence-retrieve",a));
case"link_build_sales_batch":{const hunter=await internal("/api/prospect-hunter",{city:a.city||"Copiapó",industry:a.industry||"comercio local",limit:a.limit||20,persist:true});const selected=(hunter.prospects||[]).slice(0,Math.min(Number(a.top)||5,10));const follow=new Date(Date.now()+Number(a.followup_days||1)*86400000).toISOString();const output=[];for(const p of selected){const preview=await internal("/api/preview-factory",{prospect:p});const opp=(await supa("opportunities",{method:"POST",body:JSON.stringify({prospect_id:p.id||null,name:p.name,stage:"Preview",product:preview.preview?.recommended_product||"Website Starter",value:Number(preview.preview?.estimated_value)||100000,score:p.score,next_action:"Contactar con Preview preparada",next_action_at:follow,owner_id:process.env.LINK_OWNER_ID||null})}))[0];const task=(await supa("tasks",{method:"POST",body:JSON.stringify({title:`Enviar Preview a ${p.name}`,prospect_id:p.id||null,due_at:follow,priority:p.score>=80?"alta":"media",notes:"Preview Factory lista. Revisar personalización antes de enviar.",status:"pendiente",owner_id:process.env.LINK_OWNER_ID||null})}))[0];output.push({prospect:p,preview:preview.preview,opportunity:opp,task})}return result({searched:hunter.count,selected:output.length,ready_to_contact:output})}
case"link_ask_client_ai":{const ctx=await clientContext(a.client_id);const base=(process.env.APP_URL||`https://${process.env.VERCEL_URL||"localhost"}`).replace(/\/$/,"");const r=await fetch(`${base}/api/ai-gateway`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider:"openrouter",model:process.env.OPENROUTER_MODEL||"openai/gpt-5.5",messages:[{role:"system",content:"Eres LINK Intelligence. Usa sólo el contexto del cliente. Si falta información dilo. Cita fuentes por título cuando uses contenido documental."},{role:"user",content:`CONTEXTO:${JSON.stringify(ctx)}\nPREGUNTA:${a.question}`}]})});const d=await r.json();return result({answer:d.content||d.error||"Sin respuesta",context:ctx})}
default:throw new Error("Unknown tool")}}
export default async function handler(req,res){if(req.method!=="POST")return res.status(405).json({error:"Use POST for MCP messages"});if(!auth(req))return res.status(401).json({jsonrpc:"2.0",error:{code:-32001,message:"Unauthorized"}});try{const b=req.body||{};if(b.method==="initialize")return res.status(200).json({jsonrpc:"2.0",id:b.id,result:{protocolVersion:"2024-11-05",capabilities:{tools:{listChanged:false}},serverInfo:{name:"LINK CONTROL Sales OS",version:"1.1.0"}}});if(b.method==="tools/list")return res.status(200).json({jsonrpc:"2.0",id:b.id,result:{tools:TOOLS}});if(b.method==="tools/call"){const r=await callTool(b.params?.name,b.params?.arguments||{});return res.status(200).json({jsonrpc:"2.0",id:b.id,result:r})}if(b.method==="ping")return res.status(200).json({jsonrpc:"2.0",id:b.id,result:{}});return res.status(200).json({jsonrpc:"2.0",id:b.id,error:{code:-32601,message:"Method not found"}})}catch(e){return res.status(500).json({jsonrpc:"2.0",id:req.body?.id||null,error:{code:-32000,message:e.message||"MCP error"}})}}
